apiVersion: apps/v1
kind: Deployment
metadata:
  name: drug-detector-dep
  labels:
    app: drug-detector
spec:
  replicas: 3
  selector:
    matchLabels:
      app: drug-detector
  template:
    metadata:
      labels:
        app: drug-detector
    spec:
      containers:
      - name: drug-detector-serving
        image: hotrank/drug_detector_serving
        ports:
        - name: tf-serving-port
          containerPort: 8501
