apiVersion: v1
kind: Service
metadata:
  name: drug_detector_service
spec:
  ports:
  - port: 80
    targetPort: tf_serving_port
    protocol: TCP
  selector:
    app: drug_detector
  type: LoadBalancer
